services:
  # Backend service
  backend:
    build:
      context: ./back
      target: production
    image: lesan-backend:latest
    restart: unless-stopped
    ports:
      - "1405:1405"
    env_file:
      - .env.backend
    environment:
      - APP_PORT=1405
      - ENV=production
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./back/uploads:/app/uploads
    depends_on:
      - mongo

  # Frontend service
  frontend:
    build:
      context: ./front
      target: production
    image: lesan-frontend:latest
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env.frontend
    environment:
      - APP_PORT=3005
      - NODE_ENV=production
      - LESAN_URL=http://backend:1404
      - NEXT_TELEMETRY_DISABLED=1

  # MongoDB service
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
